### ISSUE TITLE
API: Set up authorisation endpoints and JSON tokens

### ISSUE THREAD

**Issue by GreenNinjaBoy** [GreenNinjaBoy/forge-focus-api#2]
### Success Criteria:

1. 
2. sign-up, log in, log out and get user endpoints
3. JSON web tokens set up

### Tasks:

- [ ]  Add inbuilt auth views to the main urls (follow walkthrough)
- [ ]  Add JSON tokens (follow walkthrough)
- [ ]  create migrations and Migrate
- [ ]  Freeze requirements
- [ ]  Deploy and check
