### ISSUE TITLE
API: Add "refine" model and endpoints

### ISSUE THREAD

**Issue by GreenNinjaBoy** [GreenNinjaBoy/forge-focus-api#3]
### Success Criteria:

1. All tests passing
2. All endpoints functioning as expected
3. All extra filtering and ordering working

### Tasks:

- [ ]  Create app - python3 manage.py startapp APP_NAME (for this "refine" will be used)
- [ ]  Add app to settings.py
- [ ]  Write model adding class meta and dunbar string
- [ ]  Make migrations
- [ ]  Write serializer
- [ ]  Write custom permission only-owner-can
- [ ]  Write tests
- [ ]  Write views
- [ ]  Add urls
- [ ]  Add extra filters and ordering
- [ ]  Check deployed site
- [ ]  Validate code
