### ISSUE TITLE
API: Add "user goals" model and endpoints

### ISSUE THREAD

**Issue by GreenNinjaBoy** [GreenNinjaBoy/forge-focus-api#4]
### Success Criteria:

1. All tests passing
2. All endpoints functioning as expected
3. All extra filtering and ordering working

### Tasks:

 

- [ ] Create app - python3 manage.py startapp APP_NAME (user_goals)
- [ ]  Add app to settings.py
- [ ]  Write model adding class meta and dunbar string
- [ ]  Make migrations
- [ ]  Write serializer
- [ ]  Write tests
- [ ]  Write views
- [ ]  Add urls
- [ ]  Add extra filters and ordering
- [ ]  Validate code
- [ ]  Check deployed site
